# # Docker Compose configuration for a MERN stack application with authentication
# This file defines services for the application and MongoDB, including environment variables and volumes.
# It uses a custom network for communication between services and sets up persistent storage for MongoDB.
services:
  app:
    image: node:18-alpine
    container_name: mern_starter_auth
    working_dir: /app
    ports:
      - "3000:3000"
    env_file:
      - .env.docker
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - PORT=${PORT:-3000}
      - MONGO_URL=${MONGO_URL:-mongodb://mongo:27017/mern_auth}
      - JWT_SECRET=${JWT_SECRET:-your_jwt_secret_here_change_me}
      - VITE_API_BASE_URL=${VITE_API_BASE_URL:http://localhost:3000/api}
    volumes:
      - .:/app
      - /app/node_modules
      - /app/backend/node_modules
      - /app/frontend/node_modules
    command: ["sh", "/app/scripts/docker-start.sh"]
    depends_on:
      - mongo
    networks:
      - mern_network
    restart: unless-stopped

  mongo:
    image: mongo:latest
    container_name: mern_starter_auth_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=mern_auth
      # Use environment variables for MongoDB root user credentials
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME:-dbadmin}
      # This password should be changed in production
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD:-some_secure_password_change_me}
    networks:
      - mern_network
    restart: unless-stopped

volumes:
  mongo_data:

networks:
  mern_network:
    driver: bridge